name: Publish packages to github

on:
  push:
    branches:
      - main
      - ethers-v5
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_please_output: ${{ toJSON(steps.release.outputs) }}
    steps:
      - name: Run release-please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            config-file: .github/release-please/config.json
            manifest-file: .github/release-please/manifest.json
            target-branch: ${{ github.ref_name }}

      # New step to create the Mattermost message
      - name: Create the MM Message
        if: steps.release.outputs.release_created == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=$(echo ${{ steps.release.outputs.tag_name }})
          gh -R matter-labs/hardhat-zksync release view "$TAG_NAME" --json tagName,body --template '## {{.tagName}} {{"\n"}}{{.body}}' > ./release_info
          jq --null-input --arg text "$(cat ./release_info)" '{"text": $text}' > mattermost.json

      - uses: mattermost/action-mattermost-notify@master
        if: steps.release.outputs.release_created == 'true'
        env:
          MATTERMOST_USERNAME: "Hardhat Release Bot"
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_URL }}
